### ISSUE TITLE
Gnumeric.AppImage

### ISSUE THREAD

**Issue by ghost** [ecmu/gnucash.AppImage#2]
Could you also create AppImage for latest ***Gnumeric***?

Here are old scripts:

- https://github.com/fusion809/Gnumeric.AppImage

**Comment by ecmu** [comment]
I'm really sorry, the answer is no, because I don't use it and I don't have time for other projects...
You can open an issue on Gnumeric side, they can use my code of course.

**Comment by probonopd** [comment]
Yes, the best way is to ask the Gnumeric project to provide an officially-supported one.
