### ISSUE TITLE
Loading Reports crashes app

### ISSUE THREAD

**Issue by rek769** [ecmu/gnucash.AppImage#4]
Running any of the latest three builds on Puppy Linux 8.0 (Bionic) results in application crash when attempting to generate any REPORTS from the REPORTS menu item  .  Minimal info available from terminal but it is attached.  Happy to provide any other details.
[gnucash_crash.txt](https://github.com/ecmu/gnucash.AppImage/files/4616269/gnucash_crash.txt)

**Comment by ecmu** [comment]
I don't if it is a good answer but it appears that the latest GnuCash versions (4.x) are not compatible with ubuntu bionic. I performed my last build with ubuntu focal (20.04).
I close this issue because too old now. Please fill another issue if problem persist with last release.
