### ISSUE TITLE
5.0 AppImage

### ISSUE THREAD

**Issue by goldeneyeonline** [ecmu/gnucash.AppImage#5]
Might be a dumb question, but all other releases contain the AppImage that this repo seems to be about... except for the newest 5.0 Release... Is that on purpose? :-)

**Comment by ecmu** [comment]
There is no dumb question :)
There are been major changes between GnuCash 4.x and 5.0 so it now fails to compile. I do not forget that I need to review build process... when I have some time...

Sorry for the delay but any help is this is welcome of course.

**Comment by goldeneyeonline** [comment]
Thanks a lot for the clarification, that makes sense :-)
I'm sorry, I don't have a lot of compiling experience (hence I like to use AppImages :-D )

Thanks for your work on this, don't feel rushed in any way :-)
